name: Lint & Format
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@main
        with:
          toolchain: stable
          components: rustfmt

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-fmt-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-fmt-
            cargo-${{ runner.os }}-

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@main
        with:
          toolchain: stable
          components: clippy
          target: wasm32-unknown-unknown

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-clippy-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-clippy-
            cargo-${{ runner.os }}-

      - name: Run clippy
        run: cargo clippy --all-targets --all-features

      - name: Run clippy for ianaio-web-starter-net
        working-directory: crates/net
        run: |
          cargo clippy --features "http" --no-default-features
          cargo clippy --features "http,json" --no-default-features
          cargo clippy --features "websocket" --no-default-features
          cargo clippy --features "http"
          cargo clippy --features "http,json"
          cargo clippy --features "websocket"
